# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 411116b2b6b68da1e32a9f3a8b174584d3178287dd71794cef258b19cba5e4defc4898c6aea1bc4d997d8017a82a091c01af7ea8ed5c904551163c40c4936089

test:
  secret_key_base: 43f14ff9dda513b02e016e2658ab0d8402039183c63f303effd07e520604aca0bbdf14dbd4fbc53ee6d94410f3c4dce0809e98eb13a59c024f1aa3a8639aece2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
